name: Build

on:
  # Trigger on main branch push.
  push:
    branches: [ "main" ]
  
  # Triggered when pull request is created.
  pull_request:
    branches: [ "main" ]
    types: [opened]
    
  # Allow manual trigger
  workflow_dispatch: 
  
jobs:
  build:
    runs-on: ubuntu-22.04
    
    steps:
      - name: Checking out
        uses: actions/checkout@v3
        
      - name: Git install
        run: sudo apt-get install git
        
      - name: ROS install and sourcing
        run: | 
            sudo apt update && sudo apt install locales
            sudo locale-gen en_US en_US.UTF-8
            sudo update-locale LC_ALL=en_US.UTF-8 LANG=en_US.UTF-8
            export LANG=en_US.UTF-8
            sudo apt install software-properties-common
            sudo add-apt-repository universe
            sudo apt update && sudo apt install curl -y
            sudo curl -sSL https://raw.githubusercontent.com/ros/rosdistro/master/ros.key -o /usr/share/keyrings/ros-archive-keyring.gpg
            echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/ros-archive-keyring.gpg] http://packages.ros.org/ros2/ubuntu $(. /etc/os-release && echo $UBUNTU_CODENAME) main" | sudo tee /etc/apt/sources.list.d/ros2.list > /dev/null
            sudo apt update
            sudo apt upgrade
            sudo apt install ros-humble-ros-base
            sudo apt install python3-colcon-common-extensions
            
      - name: Building the package
        run: |
          source /opt/ros/humble/setup.bash
          colcon build
          source install/setup.bash
          
      - name: Running Tests
        run: |
          source /opt/ros/humble/setup.bash
          source install/setup.bash
          colcon test --pytest-with-coverage
          
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
      
          
          
            
            
